import { StyleSheet } from "react-native";

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff", 
    position: "relative",
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 80,
    alignItems: "center", 
  },
  title: {
    fontSize: 24,
    textAlign: "center",
    marginBottom: 15,
    fontWeight: "bold",
    color: "#000", 
  },
  image: {
    width: "80%", 
    height: 120,
    resizeMode: "contain",
    marginBottom: 20,
  },
  sectionTitle: {
    fontWeight: "bold",
    marginTop: 20,
    marginBottom: 10,
    fontSize: 16,
    color: "#333", 
  },
  text: {
    fontSize: 15,
    marginBottom: 5,
    color: "#666", 
    textAlign: "center", 
  },
  scheduleButton: {
    borderRadius: 16,
    marginTop: 25,
    marginBottom: 20,
    width: "90%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    overflow: 'hidden',
  },
  scheduleGradient: {
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 16,
  },
  scheduleCarImage: {
    width: 120,
    height: 75,
    resizeMode: "contain",
  },
  scheduleButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
    backgroundColor: "#1d4ed8",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 15,
    minWidth: 140,
    textAlign: "center",
  },
  buttonsContainer: {
    flexDirection: "row",
    marginTop: 10,
    gap: 15,
  },
  button: {
    backgroundColor: "#1d4ed8",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 25,
    minWidth: 120,
    alignItems: "center",
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
});