import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f9fa",
    paddingTop: 60,
  },
  header: {
    height: 56,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderColor: "#e1e8ed",
    marginTop: -10,
    backgroundColor: "#f8f9fa",
  },
  backBtn: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  headerText: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1f2937",
  },
  scrollContent: {
    padding: 20,
  },
  subtitle: {
    fontSize: 15,
    color: "#6b7280",
    marginBottom: 24,
    textAlign: "center",
  },
  categoryCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 20,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  categoryHeader: {
    marginBottom: 12,
  },
  categoryTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1f2937",
    marginBottom: 6,
  },
  categoryDescription: {
    fontSize: 14,
    color: "#6b7280",
    marginBottom: 8,
  },
  categoryInfo: {
    fontSize: 13,
    color: "#9ca3af",
    marginBottom: 4,
  },
  startButton: {
    backgroundColor: "#1d4ed8",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    marginTop: 10,
    alignItems: "center",
  },
  startButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f8f9fa",
  },
  loadingText: {
    marginTop: 12,
    fontSize: 15,
    color: "#6b7280",
  },
  quizHeader: {
    backgroundColor: "#1d4ed8",
    padding: 20,
    paddingTop: 60,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  quizTitle: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 8,
    textAlign: "center",
  },
  progressText: {
    color: "rgba(255, 255, 255, 0.9)",
    fontSize: 15,
    textAlign: "center",
    marginTop: 4,
  },
  answeredText: {
    color: "rgba(255, 255, 255, 0.8)",
    fontSize: 14,
    textAlign: "center",
    marginTop: 4,
  },
  quizContent: {
    flex: 1,
    padding: 20,
  },
  questionText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1f2937",
    marginBottom: 20,
    lineHeight: 26,
  },
  answerButton: {
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 10,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: "#e5e7eb",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  answerButtonSelected: {
    borderColor: "#1d4ed8",
    backgroundColor: "#eff6ff",
  },
  answerText: {
    fontSize: 15,
    color: "#374151",
    lineHeight: 22,
  },
  answerTextSelected: {
    color: "#1d4ed8",
    fontWeight: "600",
  },
  navigationContainer: {
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    padding: 15,
  },
  questionDots: {
    marginBottom: 15,
  },
  questionDot: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#f3f4f6",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  questionDotAnswered: {
    backgroundColor: "#eff6ff",
    borderColor: "#1d4ed8",
  },
  questionDotCurrent: {
    backgroundColor: "#1d4ed8",
    borderColor: "#1d4ed8",
  },
  questionDotText: {
    fontSize: 13,
    color: "#6b7280",
    fontWeight: "600",
  },
  questionDotTextActive: {
    color: "#fff",
    fontWeight: "700",
  },
  navigationButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  navButton: {
    flex: 1,
    backgroundColor: "#1d4ed8",
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  navButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
  },
  finishButton: {
    flex: 1,
    backgroundColor: "#059669",
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  finishButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
  },
  resultsScroll: {
    flex: 1,
  },
  resultsScrollContent: {
    padding: 20,
    paddingTop: 60,
    paddingBottom: 20,
  },
  resultHeader: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 30,
    alignItems: "center",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  resultEmoji: {
    fontSize: 48,
    marginBottom: 12,
  },
  resultTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#1f2937",
    marginBottom: 12,
  },
  resultScore: {
    fontSize: 36,
    fontWeight: "700",
    color: "#1d4ed8",
    marginBottom: 6,
  },
  resultPercentage: {
    fontSize: 18,
    color: "#6b7280",
    fontWeight: "600",
  },
  resultsSummary: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 15,
    color: "#1f2937",
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  summaryLabel: {
    fontSize: 15,
    color: "#6b7280",
  },
  summaryValue: {
    fontSize: 15,
    fontWeight: "600",
    color: "#1f2937",
  },
  correctValue: {
    color: "#059669",
  },
  wrongValue: {
    color: "#dc2626",
  },
  questionsReviewTitle: {
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 15,
    color: "#1f2937",
  },
  reviewCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderLeftWidth: 4,
    borderLeftColor: "#e5e7eb",
  },
  reviewCardCorrect: {
    borderLeftColor: "#059669",
  },
  reviewCardWrong: {
    borderLeftColor: "#dc2626",
  },
  reviewCardUnanswered: {
    borderLeftColor: "#f59e0b",
  },
  reviewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    alignItems: "center",
  },
  reviewNumber: {
    fontSize: 13,
    fontWeight: "600",
    color: "#6b7280",
  },
  reviewStatus: {
    fontSize: 13,
    fontWeight: "600",
  },
  reviewStatusCorrect: {
    color: "#059669",
  },
  reviewStatusWrong: {
    color: "#dc2626",
  },
  reviewStatusUnanswered: {
    color: "#f59e0b",
  },
  reviewQuestion: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1f2937",
    marginBottom: 12,
    lineHeight: 24,
  },
  reviewAnswer: {
    padding: 12,
    backgroundColor: "#f9fafb",
    borderRadius: 8,
    marginBottom: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  reviewAnswerCorrect: {
    backgroundColor: "#ecfdf5",
    borderColor: "#059669",
  },
  reviewAnswerWrong: {
    backgroundColor: "#fef2f2",
    borderColor: "#dc2626",
  },
  reviewAnswerText: {
    fontSize: 14,
    color: "#374151",
    flex: 1,
    lineHeight: 20,
  },
  reviewAnswerTextBold: {
    fontWeight: "600",
    color: "#1f2937",
  },
  reviewAnswerMark: {
    fontSize: 18,
    fontWeight: "700",
    marginLeft: 10,
    color: "#059669",
  },
  reviewAnswerMarkWrong: {
    fontSize: 18,
    fontWeight: "700",
    marginLeft: 10,
    color: "#dc2626",
  },
  resultsActions: {
    padding: 20,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    gap: 10,
  },
  retryButton: {
    backgroundColor: "#1d4ed8",
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  retryButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
  },
  backButton: {
    backgroundColor: "#6b7280",
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  backButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "600",
  },
});
